- name: Evaluate {{ webapp_namespace }} namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ webapp_namespace }}'
    state: present

- name: Create WebApp Operator Resources
  k8s:
    state: present
    namespace: '{{ webapp_namespace }}'
    resource_definition: '{{ lookup("file",  item ) }}'
  loop: "{{ webapp_operator_resource_items }}"

- name: Deploy custom Operator
  k8s:
    state: present
    namespace: '{{ webapp_namespace }}'
    resource_definition: '{{ lookup("template", "instructions_deploy.yml.j2") }}'

- name: Create WebApp custom resource
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'webapp.yml.j2') }}"

- name: Get webapp secure route
  k8s_info:
    kind: Route
    name: '{{ webapp_client_id }}'
    namespace: '{{ webapp_namespace }}'
    api_version: route.openshift.io/v1
  register: webapp_secure_route
  until: >-
    (webapp_secure_route.resources is defined)
    and (webapp_secure_route.resources|length>0)
  retries: 10
  delay: 30

- name: Retrieve Route
  set_fact:
    webapp_secure_route: "{{ webapp_secure_route.resources[0].spec.host }}"

- name: Create OpenShift OAuth client
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'oauthclient.yml.j2') }}"

- name: Create OpenShift Group
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'instructions_group.yml.j2') }}"
