- name: Define User Project Name
  set_fact:
    user_project: 'user{{ item }}-project'

- name: Evaluate Fuse Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'fuseconsole_subscription.yml.j2') }}"
